# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1440250246);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1440250366);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1440250126);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-zh-CN@thunderbird.mozilla.org\":{\"version\":\"31.8.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-zh-CN@thunderbird.mozilla.org.xpi\"},\"langpack-en-GB@thunderbird.mozilla.org\":{\"version\":\"31.8.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "messagingmenu%40mozilla.com:1.3.1,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.8.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1440172186000,\"rdfTime\":1436979597000},\"langpack-zh-CN@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-zh-CN@thunderbird.mozilla.org.xpi\",\"mtime\":1436980883000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1436980242000},\"langpack-en-GB@thunderbird.mozilla.org\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/langpack-en-GB@thunderbird.mozilla.org.xpi\",\"mtime\":1436980821000}}}]");
user_pref("extensions.lastAppVersion", "31.8.0");
user_pref("extensions.lastPlatformVersion", "31.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("mail.ui-rdf.version", 5);
user_pref("mailnews.database.global.datastore.id", "328e8c32-ea81-47eb-8032-3e7ea8c1303");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "重要");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "工作");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "个人信息");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "将要做");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "稍后");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("toolkit.telemetry.previousBuildID", "20150715161744");
